/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#6ffbbe",
        "surface-tint": "#565e74",
        "inverse-primary": "#bec6e0",
        "on-surface": "#dae2fd",
        "primary-container": "#131b2e",
        "tertiary": "#000000",
        "surface-container-low": "#1e293b",
        "surface": "#0b1326",
        "error": "#ef4444",
        "on-tertiary-fixed": "#002113",
        "on-primary": "#ffffff",
        "surface-container-highest": "#334155",
        "primary": "#38bdf8",
        "primary-fixed": "#dae2fd",
        "error-container": "#450a0a",
        "tertiary-container": "#064e3b",
        "on-secondary-container": "#94a3b8",
        "secondary-container": "#1e293b",
        "background": "#0b1326",
        "on-secondary-fixed-variant": "#334155",
        "on-secondary-fixed": "#dae2fd",
        "inverse-on-surface": "#0b1326",
        "surface-dim": "#0f172a",
        "outline-variant": "rgba(255,255,255,0.1)",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#1e293b",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#b9c7df",
        "on-tertiary-container": "#4edea3",
        "on-surface-variant": "#94a3b8",
        "surface-variant": "#1e293b",
        "surface-bright": "#1e293b",
        "on-primary-fixed-variant": "#38bdf8",
        "on-background": "#dae2fd",
        "on-primary-fixed": "#131b2e",
        "on-error": "#ffffff",
        "on-error-container": "#f87171",
        "outline": "#64748b",
        "surface-container-high": "#1e293b",
        "inverse-surface": "#dae2fd",
        "on-tertiary-fixed-variant": "#005236",
        "on-primary-container": "#7c839b",
        "primary-fixed-dim": "#bec6e0",
        "surface-container": "#1e293b",
        "surface-container-lowest": "rgba(30, 41, 59, 0.4)",
        "tertiary-fixed-dim": "#4edea3",
        "secondary": "#38bdf8"
      },
      fontFamily: {
        'inter': ['Inter', 'sans-serif'],
        'space': ['Space Grotesk', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
